spring.config.import=optional:file:.env[.properties]

spring.application.name=ookami
server.port=${PORT:8080}

spring.jpa.generate-ddl=true
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=${REDIS_DB}
spring.data.redis.username=${REDIS_USER}
spring.data.redis.password=${REDIS_PASSWORD}
spring.web.error.whitelabel.enabled=false

app.jwks.url=${JWKS_URL}
app.secrets.webhook=${WEBHOOK_SECRET}